services:
  db:
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - docker-volume-backup.stop-during-backup=${COMPOSE_PROJECT_NAME?err}
    networks:
      - internal
  drupal:
    labels:
      - traefik.enable=true
      - traefik.docker.network=${EXTERNAL_NETWORK?err}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME?err}.rule=Host("${APP_DOMAIN:-${COMPOSE_PROJECT_NAME?err}}")
      - com.centurylinklabs.watchtower.monitor-only=true
    networks:
      - internal
      - external
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST:-host.docker.internal}

volumes:
  db-data:
  drupal-files:
  drupal-private:

networks:
  external:
    name: ${EXTERNAL_NETWORK?err}
    external: true
  internal:
