<?php

/**
 * @file
 * Enables Group functionality for Farm organizations
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\group\Entity\GroupInterface;
use Drupal\organization\Entity\OrganizationTypeInterface;
use Symfony\Component\Routing\RouterInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gfarm_organization_type_insert(OrganizationTypeInterface $organization_type) {
  \Drupal::service('group_relation_type.manager')->clearCachedDefinitions();
}

/**
 * Implements hook_entity_operation().
 */
function gfarm_organization_entity_operation(EntityInterface $entity) {
  $operations = [];

  if ($entity->getEntityTypeId() === 'group' && \Drupal::moduleHandler()->moduleExists('views')) {
    assert($entity instanceof GroupInterface);
    if ($entity->hasPermission('access group_organization overview', \Drupal::currentUser())) {
      $router = \Drupal::service('router.no_access_checks');
      assert($router instanceof RouterInterface);
      if ($router->getRouteCollection()->get('view.group_organizations.page_1') !== NULL) {
        $operations['organizations'] = [
          'title' => t('Organizations'),
          'weight' => 20,
          'url' => Url::fromRoute('view.group_organizations.page_1', ['group' => $entity->id()]),
        ];
      }
    }
  }

  return $operations;
}

