services:
  web:
    environment:
      - DRUPAL_ENV=local
      # Fix 'Cannot parse server name for external Xdebug connection.'.
      # @see https://confluence.jetbrains.com/display/PhpStorm/Debugging+PHP+CLI+scripts+with+PhpStorm#DebuggingPHPCLIscriptswithPhpStorm-2.StarttheScriptwithDebuggerOptions
      - PHP_IDE_CONFIG=serverName=$DDEV_HOSTNAME
      # Enable Drush Launcher Xdebug compatibility.
      # @see https://github.com/drush-ops/drush-launcher#xdebug-compatibility
      - DRUSH_ALLOW_XDEBUG=1
      # Sets Drush uri, when disable_settings_management is enabled, this value
      # is not set.
      - DRUSH_OPTIONS_URI=https://$DDEV_HOSTNAME
      # Find out which hostname or IP address to use.
      # @see https://xdebug.org/docs/all_settings#discover_client_host
      - XDEBUG_CONFIG=discover_client_host=On
      # PHPUnit.
      - SIMPLETEST_BASE_URL=http://$DDEV_HOSTNAME
      - SIMPLETEST_DB=mysql://db:db@db/db
      - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
      - SYMFONY_DEPRECATIONS_HELPER=weak
      # Node compilation
      - NODE_OPTIONS=--max_old_space_size=2048
      # Use disable-dev-shm-usage instead of setting shm_usage
      # https://developers.google.com/web/tools/puppeteer/troubleshooting#tips
      # The format of chromeOptions is defined at https://chromedriver.chromium.org/capabilities
      - 'MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName":"chrome","chromeOptions":{"w3c":false,"args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://selenium-chrome:4444/wd/hub"]'
      # Nightwatch
      - DRUPAL_TEST_BASE_URL=http://$DDEV_HOSTNAME
      - DRUPAL_TEST_DB_URL=mysql://db:db@db/db
      - DRUPAL_TEST_WEBDRIVER_HOSTNAME=selenium-chrome
      - DRUPAL_TEST_WEBDRIVER_PORT=4444
      - DRUPAL_TEST_WEBDRIVER_PATH_PREFIX=/wd/hub
      - DRUPAL_TEST_CHROMEDRIVER_AUTOSTART=false
      - DRUPAL_NIGHTWATCH_SEARCH_DIRECTORY=../
      - DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES=node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
      - DRUPAL_NIGHTWATCH_OUTPUT=reports/nightwatch
      - DTT_BASE_URL=http://web
      - 'DTT_MINK_DRIVER_ARGS=["chrome", {"browserName":"chrome","chromeOptions":{"w3c":false,"args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://selenium-chrome:4444/wd/hub"]'
    extra_hosts:
      - "host.docker.internal:host-gateway"
